export type Theme = 'sand' | 'charcoal' | 'stone' | 'sky' | 'rose' | 'indigo' | 'jade' | 'forest' | 'gold' | 'space';

export const themes: Record<Theme, Record<string, string>> = {
  sky: { // Was 'blue'
    '--bg-primary': '#EFF6FF',
    '--bg-secondary': '#DBEAFE',
    '--bg-container': '#FFFFFFFF',
    '--bg-header': '#DBEAFECC',
    '--bg-footer': '#DBEAFE80',
    '--bg-input': '#FFFFFF',
    '--bg-highlight': '#FCD34D',
    '--text-primary': '#1E3A8A',
    '--text-secondary': '#3B82F6',
    '--text-header': '#1E40AF',
    '--text-on-accent': '#FFFFFF',
    '--accent-primary': '#2563EB',
    '--accent-hover': '#1D4ED8',
    '--border-primary': '#93C5FD',
    '--border-secondary': '#BFDBFE',
    '--ring-accent': '#2563EB'
  },
  stone: { // Was 'light'
    '--bg-primary': '#F9FAFB',
    '--bg-secondary': '#F3F4F6',
    '--bg-container': '#FFFFFFFF',
    '--bg-header': '#FFFFFFCC',
    '--bg-footer': '#FFFFFF80',
    '--bg-input': '#FFFFFF',
    '--bg-highlight': '#F59E0B',
    '--text-primary': '#374151',
    '--text-secondary': '#6B7280',
    '--text-header': '#111827',
    '--text-on-accent': '#FFFFFF',
    '--accent-primary': '#4F46E5',
    '--accent-hover': '#4338CA',
    '--border-primary': '#D1D5DB',
    '--border-secondary': '#E5E7EB',
    '--ring-accent': '#4F46E5'
  },
  sand: { // Was 'cream'
    '--bg-primary': '#FDF6E3',
    '--bg-secondary': '#EEE8D5',
    '--bg-container': '#FFFCF2CC',
    '--bg-header': '#EEE8D5CC',
    '--bg-footer': '#EEE8D580',
    '--bg-input': '#FFFFFF',
    '--bg-highlight': '#B58900',
    '--text-primary': '#657B83',
    '--text-secondary': '#93A1A1',
    '--text-header': '#073642',
    '--text-on-accent': '#FFFFFF',
    '--accent-primary': '#268BD2',
    '--accent-hover': '#1E6A9E',
    '--border-primary': '#93A1A1',
    '--border-secondary': '#BDB7A9',
    '--ring-accent': '#268BD2'
  },
  rose: {
    '--bg-primary': '#FFF1F2',
    '--bg-secondary': '#FFE4E6',
    '--bg-container': '#FFFFFF',
    '--bg-header': '#FFE4E6CC',
    '--bg-footer': '#FFE4E680',
    '--bg-input': '#FFFFFF',
    '--bg-highlight': '#FBCFE8',
    '--text-primary': '#831843',
    '--text-secondary': '#BE185D',
    '--text-header': '#881337',
    '--text-on-accent': '#FFFFFF',
    '--accent-primary': '#DB2777',
    '--accent-hover': '#BE185D',
    '--border-primary': '#FCC7D1',
    '--border-secondary': '#FBCFE8',
    '--ring-accent': '#DB2777'
  },
  jade: {
    '--bg-primary': '#F0FDF4',
    '--bg-secondary': '#DCFCE7',
    '--bg-container': '#FFFFFF',
    '--bg-header': '#DCFCE7CC',
    '--bg-footer': '#DCFCE780',
    '--bg-input': '#FFFFFF',
    '--bg-highlight': '#A7F3D0',
    '--text-primary': '#065F46',
    '--text-secondary': '#047857',
    '--text-header': '#064E3B',
    '--text-on-accent': '#FFFFFF',
    '--accent-primary': '#10B981',
    '--accent-hover': '#059669',
    '--border-primary': '#6EE7B7',
    '--border-secondary': '#A7F3D0',
    '--ring-accent': '#10B981'
  },
  charcoal: { // Was 'dark'
    '--bg-primary': '#121212',
    '--bg-secondary': '#1E1E1E',
    '--bg-container': '#282828CC',
    '--bg-header': '#1E1E1ECC',
    '--bg-footer': '#1E1E1E80',
    '--bg-input': '#282828',
    '--bg-highlight': '#FBBF24',
    '--text-primary': '#E0E0E0',
    '--text-secondary': '#A0A0A0',
    '--text-header': '#FFFFFF',
    '--text-on-accent': '#000000',
    '--accent-primary': '#60A5FA',
    '--accent-hover': '#3B82F6',
    '--border-primary': '#555555',
    '--border-secondary': '#444444',
    '--ring-accent': '#60A5FA'
  },
  indigo: {
    '--bg-primary': '#1E1B4B',
    '--bg-secondary': '#312E81',
    '--bg-container': '#3730A3CC',
    '--bg-header': '#312E81CC',
    '--bg-footer': '#312E8180',
    '--bg-input': '#4338CA',
    '--bg-highlight': '#A5B4FC',
    '--text-primary': '#C7D2FE',
    '--text-secondary': '#A5B4FC',
    '--text-header': '#EEF2FF',
    '--text-on-accent': '#FFFFFF',
    '--accent-primary': '#818CF8',
    '--accent-hover': '#6366F1',
    '--border-primary': '#4F46E5',
    '--border-secondary': '#4338CA',
    '--ring-accent': '#818CF8'
  },
  forest: {
    '--bg-primary': '#052e16',
    '--bg-secondary': '#064e3b',
    '--bg-container': '#065f46CC',
    '--bg-header': '#064e3bCC',
    '--bg-footer': '#064e3b80',
    '--bg-input': '#047857',
    '--bg-highlight': '#6ee7b7',
    '--text-primary': '#a7f3d0',
    '--text-secondary': '#6ee7b7',
    '--text-header': '#d1fae5',
    '--text-on-accent': '#064E3B',
    '--accent-primary': '#34d399',
    '--accent-hover': '#10b981',
    '--border-primary': '#10b981',
    '--border-secondary': '#059669',
    '--ring-accent': '#34d399'
  },
  gold: {
      '--bg-primary': '#fefce8',
      '--bg-secondary': '#fef9c3',
      '--bg-container': '#fef08aCC',
      '--bg-header': '#fef9c3CC',
      '--bg-footer': '#fef9c380',
      '--bg-input': '#FFFFFF',
      '--bg-highlight': '#facc15',
      '--text-primary': '#713f12',
      '--text-secondary': '#a16207',
      '--text-header': '#422006',
      '--text-on-accent': '#FFFFFF',
      '--accent-primary': '#ca8a04',
      '--accent-hover': '#a16207',
      '--border-primary': '#facc15',
      '--border-secondary': '#eab308',
      '--ring-accent': '#ca8a04'
  },
  space: {
    '--bg-primary': '#1e1b4b',
    '--bg-secondary': '#312e81',
    '--bg-container': '#4338caCC',
    '--bg-header': '#312e81CC',
    '--bg-footer': '#312e8180',
    '--bg-input': '#4f46e5',
    '--bg-highlight': '#c4b5fd',
    '--text-primary': '#ddd6fe',
    '--text-secondary': '#c4b5fd',
    '--text-header': '#e0e7ff',
    '--text-on-accent': '#1e1b4b',
    '--accent-primary': '#a78bfa',
    '--accent-hover': '#8b5cf6',
    '--border-primary': '#8b5cf6',
    '--border-secondary': '#7c3aed',
    '--ring-accent': '#a78bfa'
  }
};